### ISSUE TITLE
`dataset.download_BindingDB` function may need to be updated

### ISSUE THREAD

**Issue by rosa840905** [kexinhuang12345/DeepPurpose#107]
Hi, @kexinhuang12345
Thank you so much for your great work.
I found the BindingDB dataset download URL has been updated on 2021/05/01 on the website so I couldn't use the `dataset.download_BindingDB` function to download the dataset.

I guess the URL may need to be updated to https://www.bindingdb.org/bind/downloads/BindingDB_All_2021m4.tsv.zip in the `dataset.download_BindingDB` function.
Thank you.

**Comment by kexinhuang12345** [comment]
nice, do you want to make a commit to change that?

**Comment by rosa840905** [comment]
Hi, @kexinhuang12345 and @printomi
Sorry！ I missed your message.
Thank you for your reply and change.

**Comment by alex-golts** [comment]
It looks like the URL stopped working again, and now the filename needs to be changed to `BindingDB_All_2022m4.tsv.zip` 
I wonder if there is some API that can help us always know the current version. 
or otherwise, it might be good to change the code so that it expects the year and month as input from the user. Maybe it's better anyway, for reproducibility purposes.
