### ISSUE TITLE
Google Colab?

### ISSUE THREAD

**Issue by rjd55** [kexinhuang12345/DeepPurpose#121]
Hi there, Do you have an up to date guide on how to use DeepPurpose in Google Colab? I tried to use the instructions from @hima111997, but there is no longer a 'play.py' file. Cheers, Becky

**Comment by hima111997** [comment]
The play.py is a file you create. I think there are some comments about what to write in this file 

Sent from Yahoo Mail on Android 
 
  On الاثنين, أغسطس ٢٣, ٢٠٢١ at ٢:٢٨ م, ***@***.***> wrote:   


Hi there, Do you have an up to date guide on how to use DeepPurpose in Google Colab? I tried to use the instructions from @hima111997, but there is no longer a 'play.py' file. Cheers, Becky

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by hima111997** [comment]
# from DeepPurpose import oneliner
# from DeepPurpose.dataset import *
# oneliner.repurpose(*load_SARS_CoV2_Protease_3CL(), *load_antiviral_drugs(no_cid = True))

these are the comments. they are just an example you can change the code that you will write in the file and you can change the file name. But you need to change this command: 
python play.py --> python <new_file>.py (replace <new_file> with the name of the file that you will create)

**Comment by rjd55** [comment]
Thanks for your help @hima111997. I've followed the steps you suggested. But I am stuck with how to use the notebook. I copied and pasted the DeepPurpose DTI tutorial into the notebook, but I cannot import any of the packages https://colab.research.google.com/drive/1jrqvh0Co5DB8JbJJVV1B-po207iC8GMu?usp=sharing How do I import and use DeepPurpose packages and use them within the notebook. Or should I be writing all the code in the 'play.py' file?

**Comment by hima111997** [comment]
Try to write the code in play.py

Sent from Yahoo Mail on Android 
 
  On الثلاثاء, أغسطس ٢٤, ٢٠٢١ at ٥:٠٠ م, ***@***.***> wrote:   


Thanks for your help @hima111997. I've followed the steps you suggested. But I am stuck with how to use the notebook. I copied and pasted the DeepPurpose DTI tutorial into the notebook, but I cannot import any of the packages https://colab.research.google.com/drive/1jrqvh0Co5DB8JbJJVV1B-po207iC8GMu?usp=sharing How do I import and use DeepPurpose packages and use them within the notebook. Or should I be writing all the code in the 'play.py' file?


—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by rjd55** [comment]
Thank you, @kexinhuang12345 and @hima111997. I have got the code working 👍
