### ISSUE TITLE
Did you compare your DTI affinity results with other structure-based models

### ISSUE THREAD

**Issue by xuzhang5788** [kexinhuang12345/DeepPurpose#56]
Your models are all ligand-based. There are several structure-based models. Did you compare your results with them? Can your models do better than them? Thanks

**Comment by kexinhuang12345** [comment]
Hi, yes, currently, it is focused on sequence + 2D graphs. The 3D structural information is missing for the majority of the data available so it is not comparable. As DL heavily depends on data size, the current focus of DL in drug discovery mostly use accessible data format instead of hard-to-obtain 3D structures.
