### ISSUE TITLE
Drug Target Interaction Prediction with new target 

### ISSUE THREAD

**Issue by hegdesumant** [kexinhuang12345/DeepPurpose#91]
As per the documantation and dataset.py SARS-CoV 3CL Protease, SARS-CoV2 3CL Protease, Tyrosine-protein kinase Lck, ....,  MMP9 are the available protein target sequences. I want to find the interaction with some new target and data set. Something like this.

`repurpose(target="Some Target", target_name ="Some Target Name", *read_file_training_dataset_bioassay(FILE_PATH), pretrained = True)` 

Is it possible to get the prediction like this?

**Comment by kexinhuang12345** [comment]
Yes, this looks valid, you could replace the "Some Target" with the amino acid sequence and the *read_file_training_dataset_bioassay(FILE_PATH) to be the training dataset for that target. Please try both pretrained = True/False to see performance difference.

**Comment by hegdesumant** [comment]
Thanks a lot for your quick response Kexin. 
I have a doubt regarding the results.
I tried running `oneliner.repurpose(*args)` with pretrained models for few target protein sequences, run was successful and got the result files. As the output it generated 6 different files. CNN_CNN, Daylight_AAC, Morgan_CNN, Morgan_AAC, MPNN_CNN and aggregation. All 6 result files have similar output pattern but has different binding scores. In this case prediction of which model is more appropriate? Also If I take the average of all 6 prediction scores and re arrange the rankings, will it give generalized prediction score?

**Comment by kexinhuang12345** [comment]
Hi, sorry for the late response. Yeah, you can think of different models looking at different signals. So, there is no absolute better or not, depending on the data at hand. So yes, an average or a max + average / 2 is a good aggregated score. You can also try more learnable ways to do it. But the main idea for real world practice is to narrow down a large search space to a small space which contains all high candidates for all models since they look at different things.
