### ISSUE TITLE
Is it possible to change the dimensions of encoding?

### ISSUE THREAD

**Issue by xuzhang5788** [kexinhuang12345/DeepPurpose#96]
I found your the default dimension of Morgan encoding is 1024. If I want to change it to a larger number, How can I change drug_encoding = 'Morgan'?
I also want to have an option on useFeatures=True/False. (AllChem.GetMorganFingerprintAsBitVect(m, 2, nBits=dim, useFeatures=False). The default setting is False.

Thanks a lot.

**Comment by albertma-evotec** [comment]
you could go to util.py file smiles2morgan function and change nBits = 2048
Inside the function you can set useFeatures=False/True in GetMorganFingerprintAsBitVect()
You will also need to make sure input_dim_drug is 2048 when you generate your configuration
```
config = utils.generate_config(drug_encoding = drug_encoding, 
                         target_encoding = target_encoding, 
                         cls_hidden_dims = [1024,1024,512],
                        input_dim_drug=2048, ....
```

**Comment by xuzhang5788** [comment]
@albertma-evotec 
I changed util.py file smiles2morgan function to nBits = 2048, but I still got 1024 Bits.

I upgraded the library and also ran python setup.py install, unfortunately, I still got 1024 Bits

**Comment by kexinhuang12345** [comment]
Hi, thanks for providing the solution. Yes, this is exactly right. Note that as you change the library in your local machine with the source library, it is not going to be on the official DeepPurpose pip version. I think the issue is you are still accessing the pip installed version of DeepPurpose instead of the local source versions. You can try to run the code in the directory of the source directory.

**Comment by albertma-evotec** [comment]
@xuzhang5788  if you are using jupyter notebook, you need to restart the kernel to take effect.
